/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminSuggestionsNewRouteImport } from './routes/admin/suggestions/new'
import { Route as AdminSuggestionsIdEditRouteImport } from './routes/admin/suggestions/$id.edit'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuggestionsNewRoute = AdminSuggestionsNewRouteImport.update({
  id: '/admin/suggestions/new',
  path: '/admin/suggestions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuggestionsIdEditRoute = AdminSuggestionsIdEditRouteImport.update({
  id: '/admin/suggestions/$id/edit',
  path: '/admin/suggestions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/topics': typeof TopicsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/suggestions/new': typeof AdminSuggestionsNewRoute
  '/admin/suggestions/$id/edit': typeof AdminSuggestionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/topics': typeof TopicsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin': typeof AdminIndexRoute
  '/admin/suggestions/new': typeof AdminSuggestionsNewRoute
  '/admin/suggestions/$id/edit': typeof AdminSuggestionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/topics': typeof TopicsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/suggestions/new': typeof AdminSuggestionsNewRoute
  '/admin/suggestions/$id/edit': typeof AdminSuggestionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/topics'
    | '/auth/callback'
    | '/auth/error'
    | '/admin/'
    | '/admin/suggestions/new'
    | '/admin/suggestions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/topics'
    | '/auth/callback'
    | '/auth/error'
    | '/admin'
    | '/admin/suggestions/new'
    | '/admin/suggestions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/topics'
    | '/auth/callback'
    | '/auth/error'
    | '/admin/'
    | '/admin/suggestions/new'
    | '/admin/suggestions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  TopicsRoute: typeof TopicsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSuggestionsNewRoute: typeof AdminSuggestionsNewRoute
  AdminSuggestionsIdEditRoute: typeof AdminSuggestionsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suggestions/new': {
      id: '/admin/suggestions/new'
      path: '/admin/suggestions/new'
      fullPath: '/admin/suggestions/new'
      preLoaderRoute: typeof AdminSuggestionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suggestions/$id/edit': {
      id: '/admin/suggestions/$id/edit'
      path: '/admin/suggestions/$id/edit'
      fullPath: '/admin/suggestions/$id/edit'
      preLoaderRoute: typeof AdminSuggestionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  TopicsRoute: TopicsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSuggestionsNewRoute: AdminSuggestionsNewRoute,
  AdminSuggestionsIdEditRoute: AdminSuggestionsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
